### ISSUE TITLE
Jcenter doesn't exist anymore

### ISSUE THREAD

**Issue by Moncader** [plaidev/karte-flutter#23]
This project is relying on jcenter for its Android dependencies.
However jcenter doesn't exist anymore and everything needed to be moved to mavenCentral.

https://developer.android.com/studio/build/jcenter-migration

Currently when trying to build the project it fails due to jcenter not being found.
The document says that they will provide readonly downloads indefinitely, however officially everything needs to be moved to a different repository.

**Comment by wasnot** [comment]
@Moncader 

Thank you for the information.

As you said, we missed the transition to mavenCentral.
Our android sdk has already been uploaded to mavenCentral, but currently flutter could not refer to the latest SDK.

I will transfer it later.

**Comment by wasnot** [comment]
The description of jcenter has been deleted with the release on March 14th.
