### ISSUE TITLE
[karte_core] The version set in pubspec.yaml is wrong

### ISSUE THREAD

**Issue by peripn** [plaidev/karte-flutter#8]
`karte_core` の `pubspec.yaml` に含まれる Flutter バージョンの指定が間違っているのではないでしょうか。
（Dart 2.12.0 かつ Flutter 1.20.0 の組み合わせにすることは不可能なため）

## Detailed Description

`pubspec.yaml` には以下の記述があります。

```yaml
environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.20.0"
```

また、Developer Portal (https://developers.karte.io/docs/setup-flutter-sdk) には次のようにあります。
> 本SDKは、Flutter 1.20 以上、Dart 2.12.0 以上で動作することを確認しております。

しかしながら Flutter 1.20.0 に同梱されているのは Dart SDK は 2.12.0 よりも古いものであり、
かつ `flutter` コマンドの仕様上、Flutter は Flutter SDK に同梱されている Dart SDK を使用するようになっていることから
Flutter 1.20.0 では `pubspec.yaml` に書かれた条件を満たせず、実際には `karte_core` を動作されることは不可能かと思います。

また pub.dev を参照 (https://pub.dev/packages/karte_core) すると、`karte_core` は Null Safety に対応していることとなっています。
（実際に、 `karte_core.dart` などで Null許容型を使用している箇所があります）
しかしながら Null Safety の有効化には Flutter 2.0.0 以上が必要なため Flutter 1.20.0 ではこれを有効にできない認識です。
（こちらは、もしかすると何らかの方法で Flutter 1.20.0 かつ Dart SDK 2.12.0 の組み合わせにできれば Null Safety 機能を使えるのでしょうか？）

実際は Flutter 2.0.0 以上でないと実行することができないのではないでしょうか？
`karte_core` は Flutter 1.20.0 で、どのようにして動作確認を行っているのでしょうか？

## Possible Implementation

```diff
 environment:
   sdk: '>=2.12.0 <3.0.0'
-  flutter: ">=1.20.0"
+  flutter: ">=2.0.0"
```

**Comment by wasnot** [comment]
@peripng 

ご指摘いただきありがとうございます。

ご指摘の通り、Flutter 1.22.0とDart 2.12.0の組み合わせは通常不可能なため、
検証・推奨環境として記載している、Developer Portalについては修正漏れでした。
修正させていただきます。

pubspecの依存記述につきましては、アップデートの際に社内でも検討いたしました。
本ライブラリはPlatform pluginとして開発されております。
そのため、Dartバージョンへの依存制約は言語仕様に関する依存（今回はnull-safety）の条件を示し、
Flutterバージョンへの依存制約はFlutterフレームワークやEngine、および各プラットフォームへのEmbeddingへの依存の条件を示しているものと考えました。
つまり、本ライブラリでは現在、言語としてはDart2.12以降を要求しますが、Flutterフレームワークに関しては1.20以降のみを要求しています。
そのため、現状このような形とさせていただいておりました。

我々はFlutter / Dartのpackageの依存制約の文化を十分に理解できていませんが、
通常、依存関係の制約は、それぞれリンク時にエラーが起きない最低限のバージョンを指定し、現実的な組み合わせまで考慮することは少ないのではないかと考えました。
（DartとFlutterのバージョンの明確な対応表を見つけられなかったこともございます。）
また、本SDKはサービス導入に必須となるようなパッケージのため、過剰な制約は導入への障害となるため意図的に避けるようにもしておりました。

ご意見や他のライブラリの依存記述等を踏まえ、引き続き修正等対応を検討させていただきたいと思います。
追加で何かございましたら、ご意見やご助言等いただけますと大変助かります。

---

ご質問に関してですが、ご指摘の通りFlutter SDKでは現在、同梱されたDartを使用するようになっているため、
Flutter1.20とDart 2.12の組み合わせは通常起こり得ません。
そのため、特に組み合わせの検証は行なっておりません。

弊社では以下の検証を行いました。

- FlutterのNative側コード(Java/Objective-c等)とpluginのNative側コードが1.20~2系で問題なくビルド・動作すること
    - 検証の際は、Dart部分やpubspecの制約がリリース時とは異なる場合がありました
- Dart2.12以上においてDartで記述したinterfaceが問題なくビルド・動作すること

それでも、全てのバージョンでの検証ができている体制ではなく、ご不便をおかけしているケースもございます。
それについては、ご迷惑をおかけしておりますが、社内のリソースの事情もございます上、ご理解いただけますと幸いです。


FlutterやDartは多くがOSSで構成されているため、Dartのみのバージョン変更も理論上不可能ではないと考えられます。
（実際にFlutter内部の依存ライブラリを調整することで依存解決はできました）
Dart 2.12以降でも、null-safetyでないパッケージを混在させることは可能です。
ただし、その場合はご懸念の通りnull-safetyの機能や恩恵を十分に活かすことができないと考えられます。
そしてそれは正規のFlutterとは言いづらいので、サポートしていると表現することに意味がないというご指摘はごもっともです。


改めまして、ご質問・ご助言いただきありがとうございます。
